from enum import IntEnum


class Command(IntEnum):
    FW_VERSION = 0
    GET_VALUES = 4
    SET_DUTY = 5
    SET_CURRENT = 6
    SET_CURRENT_BRAKE = 7
    SET_RPM = 8
    SET_POS = 9
    SET_HANDBRAKE = 10
    SET_DETECT = 11
    SET_SERVO_POS = 12
    PRINT = 21
    ROTOR_POSITION = 22
    ALIVE = 30
    GET_DECODED_PPM = 31
    GET_DECODED_ADC = 32
    GET_DECODED_CHUK = 33
    FORWARD_CAN = 34
    GET_DECODED_BALANCE = 79
    GET_VALUES_SETUP = 47
    GET_VALUES_SELECTIVE = 50
    PING_CAN = 62
    TERMINAL_CMD_SYNC = 64
    GET_IMU_DATA = 65
    SET_CURRENT_REL = 84
