from enum import IntEnum


class Command(IntEnum):
    """Nomor command persis seperti ``COMM_PACKET_ID`` di ``datatypes.h``
    (vedderb/bldc). Urutan dan nilai harus sama persis dengan firmware."""

    FW_VERSION = 0
    JUMP_TO_BOOTLOADER = 1
    ERASE_NEW_APP = 2
    WRITE_NEW_APP_DATA = 3
    GET_VALUES = 4
    SET_DUTY = 5
    SET_CURRENT = 6
    SET_CURRENT_BRAKE = 7
    SET_RPM = 8
    SET_POS = 9
    SET_HANDBRAKE = 10
    SET_DETECT = 11
    SET_SERVO_POS = 12
    SET_MCCONF = 13
    GET_MCCONF = 14
    GET_MCCONF_DEFAULT = 15
    SET_APPCONF = 16
    GET_APPCONF = 17
    GET_APPCONF_DEFAULT = 18
    SAMPLE_PRINT = 19
    TERMINAL_CMD = 20
    PRINT = 21
    ROTOR_POSITION = 22
    EXPERIMENT_SAMPLE = 23
    DETECT_MOTOR_PARAM = 24
    DETECT_MOTOR_R_L = 25
    DETECT_MOTOR_FLUX_LINKAGE = 26
    DETECT_ENCODER = 27
    DETECT_HALL_FOC = 28
    REBOOT = 29
    ALIVE = 30
    GET_DECODED_PPM = 31
    GET_DECODED_ADC = 32
    GET_DECODED_CHUK = 33
    FORWARD_CAN = 34
    SET_CHUCK_DATA = 35
    CUSTOM_APP_DATA = 36
    NRF_START_PAIRING = 37
    GPD_SET_FSW = 38
    GPD_BUFFER_NOTIFY = 39
    GPD_BUFFER_SIZE_LEFT = 40
    GPD_FILL_BUFFER = 41
    GPD_OUTPUT_SAMPLE = 42
    GPD_SET_MODE = 43
    GPD_FILL_BUFFER_INT8 = 44
    GPD_FILL_BUFFER_INT16 = 45
    GPD_SET_BUFFER_INT_SCALE = 46
    GET_VALUES_SETUP = 47
    SET_MCCONF_TEMP = 48
    SET_MCCONF_TEMP_SETUP = 49
    GET_VALUES_SELECTIVE = 50
    GET_VALUES_SETUP_SELECTIVE = 51
    EXT_NRF_PRESENT = 52
    EXT_NRF_ESB_SET_CH_ADDR = 53
    EXT_NRF_ESB_SEND_DATA = 54
    EXT_NRF_ESB_RX_DATA = 55
    EXT_NRF_SET_ENABLED = 56
    DETECT_MOTOR_FLUX_LINKAGE_OPENLOOP = 57
    DETECT_APPLY_ALL_FOC = 58
    JUMP_TO_BOOTLOADER_ALL_CAN = 59
    ERASE_NEW_APP_ALL_CAN = 60
    WRITE_NEW_APP_DATA_ALL_CAN = 61
    PING_CAN = 62
    APP_DISABLE_OUTPUT = 63
    TERMINAL_CMD_SYNC = 64
    GET_IMU_DATA = 65
    BM_CONNECT = 66
    BM_ERASE_FLASH_ALL = 67
    BM_WRITE_FLASH = 68
    BM_REBOOT = 69
    BM_DISCONNECT = 70
    BM_MAP_PINS_DEFAULT = 71
    BM_MAP_PINS_NRF5X = 72
    ERASE_BOOTLOADER = 73
    ERASE_BOOTLOADER_ALL_CAN = 74
    PLOT_INIT = 75
    PLOT_DATA = 76
    PLOT_ADD_GRAPH = 77
    PLOT_SET_GRAPH = 78
    GET_DECODED_BALANCE = 79
    BM_MEM_READ = 80
    WRITE_NEW_APP_DATA_LZO = 81
    WRITE_NEW_APP_DATA_ALL_CAN_LZO = 82
    BM_WRITE_FLASH_LZO = 83
    SET_CURRENT_REL = 84
    CAN_FWD_FRAME = 85
    SET_BATTERY_CUT = 86
    SET_BLE_NAME = 87
    SET_BLE_PIN = 88
    SET_CAN_MODE = 89
    GET_IMU_CALIBRATION = 90
    GET_MCCONF_TEMP = 91
    GET_CUSTOM_CONFIG_XML = 92
    GET_CUSTOM_CONFIG = 93
    GET_CUSTOM_CONFIG_DEFAULT = 94
    SET_CUSTOM_CONFIG = 95
    BMS_GET_VALUES = 96
    BMS_SET_CHARGE_ALLOWED = 97
    BMS_SET_BALANCE_OVERRIDE = 98
    BMS_RESET_COUNTERS = 99
    BMS_FORCE_BALANCE = 100
    BMS_ZERO_CURRENT_OFFSET = 101
    JUMP_TO_BOOTLOADER_HW = 102
    ERASE_NEW_APP_HW = 103
    WRITE_NEW_APP_DATA_HW = 104
    ERASE_BOOTLOADER_HW = 105
    JUMP_TO_BOOTLOADER_ALL_CAN_HW = 106
    ERASE_NEW_APP_ALL_CAN_HW = 107
    WRITE_NEW_APP_DATA_ALL_CAN_HW = 108
    ERASE_BOOTLOADER_ALL_CAN_HW = 109
    SET_ODOMETER = 110
    PSW_GET_STATUS = 111
    PSW_SWITCH = 112
    BMS_FWD_CAN_RX = 113
    BMS_HW_DATA = 114
    GET_BATTERY_CUT = 115
    BM_HALT_REQ = 116
    GET_QML_UI_HW = 117
    GET_QML_UI_APP = 118
    CUSTOM_HW_DATA = 119
    QMLUI_ERASE = 120
    QMLUI_WRITE = 121
    IO_BOARD_GET_ALL = 122
    IO_BOARD_SET_PWM = 123
    IO_BOARD_SET_DIGITAL = 124
    BM_MEM_WRITE = 125
    BMS_BLNC_SELFTEST = 126
    GET_EXT_HUM_TMP = 127
    GET_STATS = 128
    RESET_STATS = 129
    LISP_READ_CODE = 130
    LISP_WRITE_CODE = 131
    LISP_ERASE_CODE = 132
    LISP_SET_RUNNING = 133
    LISP_GET_STATS = 134
    LISP_PRINT = 135
    BMS_SET_BATT_TYPE = 136
    BMS_GET_BATT_TYPE = 137
    LISP_REPL_CMD = 138
    LISP_STREAM_CODE = 139
    FILE_LIST = 140
    FILE_READ = 141
    FILE_WRITE = 142
    FILE_MKDIR = 143
    FILE_REMOVE = 144
    LOG_START = 145
    LOG_STOP = 146
    LOG_CONFIG_FIELD = 147
    LOG_DATA_F32 = 148
    SET_APPCONF_NO_STORE = 149
    GET_GNSS = 150
    LOG_DATA_F64 = 151
    LISP_RMSG = 152
    SHUTDOWN = 156
    FW_INFO = 157
    CAN_UPDATE_BAUD_ALL = 158
    MOTOR_ESTOP = 159


# Bit mask untuk GET_VALUES / GET_VALUES_SELECTIVE (persis urutan di
# commands.cpp ``case COMM_GET_VALUES``). Nomor bit = indeks field.
class ValueMask:
    TEMP_MOS = 1 << 0
    TEMP_MOTOR = 1 << 1
    CURRENT_MOTOR = 1 << 2
    CURRENT_IN = 1 << 3
    ID = 1 << 4
    IQ = 1 << 5
    DUTY_NOW = 1 << 6
    RPM = 1 << 7
    V_IN = 1 << 8
    AMP_HOURS = 1 << 9
    AMP_HOURS_CHARGED = 1 << 10
    WATT_HOURS = 1 << 11
    WATT_HOURS_CHARGED = 1 << 12
    TACHOMETER = 1 << 13
    TACHOMETER_ABS = 1 << 14
    FAULT_CODE = 1 << 15
    POSITION = 1 << 16
    VESC_ID = 1 << 17
    TEMP_MOS_1_2_3 = 1 << 18
    VD = 1 << 19
    VQ = 1 << 20
    STATUS = 1 << 21

    # Backward-compatible convenience alias. On the VESC wire these are two
    # independent fields, not one grouped bit.
    VD_VQ = VD | VQ

    # Semua field yang diketahui (bit 0..20).
    ALL = (1 << 22) - 1


# Bit mask untuk GET_VALUES_SETUP (urutan di ``case COMM_GET_VALUES_SETUP``).
class SetupMask:
    TEMP_MOS = 1 << 0
    TEMP_MOTOR = 1 << 1
    CURRENT_MOTOR = 1 << 2
    CURRENT_IN = 1 << 3
    DUTY_NOW = 1 << 4
    RPM = 1 << 5
    SPEED = 1 << 6
    V_IN = 1 << 7
    BATTERY_LEVEL = 1 << 8
    AMP_HOURS = 1 << 9
    AMP_HOURS_CHARGED = 1 << 10
    WATT_HOURS = 1 << 11
    WATT_HOURS_CHARGED = 1 << 12
    TACHOMETER = 1 << 13
    TACHOMETER_ABS = 1 << 14
    POSITION = 1 << 15
    FAULT_CODE = 1 << 16
    VESC_ID = 1 << 17
    NUM_VESCS = 1 << 18
    BATTERY_WH = 1 << 19
    ODOMETER = 1 << 20
    UPTIME_MS = 1 << 21

    ALL = (1 << 22) - 1


# Bit mask untuk GET_IMU_DATA (urutan di ``case COMM_GET_IMU_DATA``).
class ImuMask:
    ROLL = 1 << 0
    PITCH = 1 << 1
    YAW = 1 << 2
    ACC_X = 1 << 3
    ACC_Y = 1 << 4
    ACC_Z = 1 << 5
    GYRO_X = 1 << 6
    GYRO_Y = 1 << 7
    GYRO_Z = 1 << 8
    MAG_X = 1 << 9
    MAG_Y = 1 << 10
    MAG_Z = 1 << 11
    Q0 = 1 << 12
    Q1 = 1 << 13
    Q2 = 1 << 14
    Q3 = 1 << 15

    ALL = (1 << 16) - 1
