[env:stm32f103rc]
platform = ststm32
board = genericSTM32F103RC
framework = stm32cube
board_build.ldscript = stm32f103rc_v11.ld
upload_protocol = stlink
debug_tool = stlink
# Reserve final 8 KiB (four 2-KiB pages) (0x0803E000..0x0803FFFF) for persistent config.
board_upload.maximum_size = 253952
extra_scripts = pre:extra_script.py
build_flags =
    -DSTM32F103xE
    -DUSE_HAL_DRIVER
    -Isrc
    -O3
    -fno-math-errno
    -Wall
    -Wextra
    -Wshadow
    -Wdouble-promotion
    -Wformat=2
    -Werror=return-type
    -Werror=implicit-function-declaration
    -Wno-unused-parameter
    -Wno-pedantic
build_unflags = -Os
monitor_speed = 115200
